In [ ]:
import torch

In [ ]:
random_tensor = torch.rand(7, 7)
random_tensor, random_tensor.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

In [ ]:
tensor2 = torch.rand(1, 7)
tensor2

tensor([[0.3416, 0.9816, 0.7970, 0.9582, 0.1786, 0.7111, 0.1979]])

In [ ]:
tensor_mult = random_tensor @ tensor2.T
tensor_mult

tensor([[1.6981],
        [1.8550],
        [2.8666],
        [1.3470],
        [2.7245],
        [1.5874],
        [2.0757]])

In [ ]:
torch.manual_seed(0)

ten1 = torch.rand(1, 7)
ten2 = torch.rand(7, 1)

tensor_mult = ten1 @ ten2
tensor_mult

tensor([[1.1173]])

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.manual_seed(1234)
cuda = torch.device('cuda')

ten1 = torch.rand(1, 7).to(device=cuda)
ten2 = torch.rand(7, 1).to(device=cuda)

tensor_mult = ten1 @ ten2
tensor_mult

tensor([[1.4202]], device='cuda:0')

In [ ]:
ten1 = torch.rand(2,3).to(device=cuda)
ten1

tensor([[0.1872, 0.0340, 0.9442],
        [0.8802, 0.0012, 0.5936]], device='cuda:0')

In [ ]:
ten2 = torch.rand(2,3).to(device=cuda)
ten2


tensor([[0.4158, 0.4177, 0.2711],
        [0.6923, 0.2038, 0.6833]], device='cuda:0')

In [ ]:
mat_mul = ten1 @ ten2.T
mat_mul

tensor([[0.3480, 0.7817],
        [0.5274, 1.0152]], device='cuda:0')

In [ ]:
mat_mul.shape

torch.Size([2, 2])

In [ ]:
mat_mul.max()

tensor(1.0152, device='cuda:0')

In [ ]:
mat_mul.min()

tensor(0.3480, device='cuda:0')

In [ ]:
mat_mul.argmax()

tensor(3, device='cuda:0')

In [ ]:
mat_mul.argmin()

tensor(0, device='cuda:0')

In [ ]:
torch.manual_seed(7)

tensor = torch.rand(1, 1, 1, 10)
print(tensor)
print(tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])


In [ ]:
squeezed_tensor = torch.squeeze(tensor)
print(squeezed_tensor)
print(squeezed_tensor.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
